export default WebService = {
  BASE_URL: "https://api.trendii.com/v1/",
  // BASE_URL: "https://uatapi.trendii.com/v1/",
  IMAGEBASEURL: "https://trendii.com/images/",
  // IMAGEBASEURL: "https://uat.trendii.com/images/",
  LOGIN: "auth/login",
  SOCIALLOGIN: "auth/social-login",
  REGISTER: "auth/register",
  FORGOTPASS: "auth/forgotPassword",
  TERMS: "auth/terms",
  FEEDS: "auth/get-feed",
  BINGFEEDDATA: "api/bing-image-feed-data",
  LIKEDISLIKETHUMB: "api/bing-image-thumb-action",
  INSPIRATIONS: "auth/inspiration",
  INSPIRATIONSITEMS: "auth/inspiration-items",
  ADD_NEW_INSPIRATION_CATEGORY: "auth/add-new-inspiration-category",
  ADDTOFAV: "api/add-to-favourite",
  REFERFRIEND: "api/refer-friend",
  PRODUCTDETAIL: "auth/product-detail",
  DISCOVERSEARCH: "auth/discover-search",
  BINGSEARCH: "auth/bing-search",
  USER_DETAILS: "api/get-user-details",
  GET_USER_EDIT_PROFILE: "api/get-user-edit-profile",
  UPDATE_USER_PROFILE: "api/update-user-profile",
  CHANGE_PASSWORD: "api/change-password",
  UPDATE_EMAIL_PREFERNECE: "api/update-user-email-preferences",
  PAYMENT_HISTORY: "api/payment-history",
  GET_USER_INSPIRATION: "api/get-user-inspirations",
  DELETE_INSPIRATIONS: "api/delete-inspirations",
  USERFAVOURITTES: "api/user-favourites",
  USER_REWARDS: "api/user-rewards",
  DELETEWISHLISTITEM: "api/delete-favourite-item",
  VERIFY_ADD_USER_PAYPAL:"api/verify-and-add-user-paypal-account",
  SET_DEFAULT_PAYMENTCARD:"api/set-default-paymentcard",
  DELETE_PAYMENT_ACCOUNT_CARD:"api/delete-payment-card",
  GET_TRANSFER_DETAILS:"api/get-transfer-details",
  PAYMENT_WITHDRAW:"api/payment-withdraw",
  GETNOTIFICATIONS: "api/get-user-notification",
  DELETE_NOTIFICATIONS: "api/delete-notification",
  READ_NOTIFICATIONS: "api/read-notification",
  SET_REFERFRIEND_ID:"api/referral-token",
  IMAGESCRAPPER: "auth/image-scrapper",
  PRODUCT_BUY_TRACK: "auth/product-buy-button-track",
};
